Skill.upsert_all([
  { id: 301, name: "Emblema", description: "Tutti i combattenti alleati, che rispondono alla via di alleanza del Nexus ed entro X da esso, possono utilizzare il valore di Struttura (senza contare eventuali ferite) del Nexus per effettuare le loro prove di COR/DIS.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 302, name: "Fede", description: "Un fedele alleato, che risponde alla via di alleanza del Nexus ed entro la sua Area d’Accesso, può, durante la sua attivazione, distruggere il Nexus per recuperare immediatamente X punti fede. Uno stesso fedele può sacrificare così un solo Nexus per turno, e questa azione NON conta come aver attivato il Nexus. Si veda la nota legata a Martire a pag.XX.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 303, name: "Guardiano", description: "Prima di ogni tiro per ferire che il Nexus deve subire si lanci un dado. Con un risultato di X o più il tiro per ferire è annullato.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 304, name: "Icona", description: "I fedeli alleati che rispondono alla via di alleanza del Nexus e che hanno il Nexus a portata della propria aura di fede, recuperano X punti fede addizionali durante la fase mistica.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 305, name: "Inviolabile", description: "Questo nexus non può essere Forzato.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: nil },
  { id: 306, name: "Mana", description: "Un mago alleato, che risponde alla via di alleanza del Nexus ed entro la sua Area d’Accesso, può, durante la sua attivazione, distruggere il Nexus per recuperare immediatamente X gemme di mana, suddivise a sua scelta fra gli elementi che domina. Uno stesso mago può sacrificare così un solo Nexus per turno, e questa azione NON conta come aver attivato il Nexus. Si veda la nota legata a Devozione a pag.XX.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 307, name: "Ostile", description: "Quando il Nexus causa un tiro per ferire ad un combattente nei confronti del quale è ostile, il risultato del tiro per ferire è letto una riga più in basso nella tabella delle ferite. Questo effetto si cumula con effetti simili.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 308, name: "Riparazione", description: "Durante il mantenimento si lanci 1D6 per ogni Nexus con questa abilità che ha perso punti struttura. Con X o più il Nexus recupera 1 punto struttura.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 309, name: "Risorsa", description: "Durante il mantenimento si lanci 1D6 per ogni Nexus con questa abilità. Con un risultato di X o più il Nexus recupera una carica. Questa abilità non permette al Nexus di avere più cariche di quelle previste dalla voce cariche.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 310, name: "Rovina", description: "Durante il mantenimento si lanci 1D6 per ogni Nexus con questa abilità. Con X o più il Nexus perde 1 punto struttura.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 311, name: "Santuario", description: "Una volta che il Nexus viene posizionato sul campo, nessun Esploratore e nessun Nexus nemico può essere posizionato a meno di X da esso. Se un Nexus dispone di Santuario ed Ostile/Y, allora tutti i combattenti che dispongono del parametro Y subiscono un malus di -1 INI, ATT, DIF e TIR finché si trovano entro X dal Nexus. Questa penalità si cumula con altre penalità simili.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: "X" },
  { id: 312, name: "Soggiogato", description: "Un Nexus soggiogato è legato, all’inizio di ogni turno, al combattente suo alleato la cui DIS è usata per effettuare il tiro di tattica. Se questo combattente può essere Catalizzatore del Nexus, egli può allora attivarlo senza essere a portata d’Accesso. Uno stesso combattente può così essere legato a più Nexus soggiogati e può attivarne quanti ne vuole nel corso di uno stesso turno.​ Un Nexus soggiogato può comunque essere Forzato.", created_at: "2025-12-28T14:45:12Z", updated_at: "2025-12-28T14:45:12Z", value: nil },
])
